name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Run Build Script
      run: |
        pwsh ./build-app.ps1  
        
    - name: Upload test results to GitHub Actions
      uses: sreechith-gh/junit-report-action@v1
      with:
        test_report: TECHNICAL-ASSIGMENT/Assigment/AssigmentTests/TestResults/test-results.xml
          
